# Generated by Django 4.0.1 on 2022-11-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='descrpción_sospechoso',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
